import { useEffect, useState } from 'react'
import Navbar from '../components/Navbar'
import { recommendationsApi } from '../api/api'
import { colors } from '../theme'
import PageLoader from '../components/PageLoader'
import PageHeader from '../components/PageHeader'
import ErrorBanner from '../components/ErrorBanner'
import ReactMarkdown from 'react-markdown'


const rows = [
  {
    key: 'Book',
    label: 'All-time recommendation',
    tag: 'All-time pick',
    color: colors.warmOak,
    bg: '#f5ede0',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="#A57650" strokeWidth="2" width="15" height="15">
        <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/>
        <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/>
      </svg>
    ),
    desc: () => 'This is the book that was made for you. Based on everything you\'ve read, this is your perfect match.',
  },
  {
    key: 'RecentBook',
    label: 'Recent recommendation',
    tag: 'Read next',
    color: colors.blueberry,
    bg: '#e0e4ec',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="#414757" strokeWidth="2" width="15" height="15">
        <circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>
      </svg>
    ),
    desc: () => 'For what you\'re in the mood for right now, this is exactly where you should be.',
  },
  {
    key: 'Author',
    label: 'Author to explore',
    tag: 'Explore',
    color: colors.berry,
    bg: '#fbeaea',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="#851C24" strokeWidth="2" width="15" height="15">
        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/>
        <circle cx="12" cy="7" r="4"/>
      </svg>
    ),
    desc: () => 'Their writing style and themes align perfectly with your taste.',
  },
  {
    key: 'Interest',
    label: 'Your reading interest',
    tag: 'Deduced from your library',
    color: colors.sage,
    bg: '#e4ede0',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="#84896D" strokeWidth="2" width="15" height="15">
        <circle cx="11" cy="11" r="8"/>
        <line x1="21" y1="21" x2="16.65" y2="16.65"/>
      </svg>
    ),
    desc: () => 'Your library reveals a deep love for layered narratives and rich storytelling.',
  },
  {
    key: 'Personality',
    label: 'Your reader personality',
    tag: 'Your archetype',
    color: colors.blueberry,
    bg: '#e0e4ec',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="#414757" strokeWidth="2" width="15" height="15">
        <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>
      </svg>
    ),
    desc: () => 'Curious, reflective and creative — you read to understand the world, not just to escape it.',
  },
  {
    key: 'FictionalCharacter',
    label: 'Your fictional character',
    tag: 'Your match',
    color: colors.umberBrown,
    bg: '#f5ede0',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="#8C6046" strokeWidth="2" width="15" height="15">
        <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
      </svg>
    ),
    desc: () => 'Determined, brilliant and always with a book in hand — you two would get along perfectly.',
  },
]

export default function RecommendationsPage({ onLogout }) {
  const [recommendation, setRecommendation] = useState(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')

  const fetchRecommendation = async () => {
    setError('')
    setGenerating(true)
    try {
      const data = await recommendationsApi.get()
      setRecommendation(data)
    } catch (e) {
      setError('Could not generate recommendation. Make sure you have books in your library.')
    }
    setGenerating(false)
    setLoading(false)
  }

  useEffect(() => {
    fetchRecommendation()
  }, [])

  const today = new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })

  if (loading) return <PageLoader message="Reading your library..." />

  return (
    <div style={{ minHeight: '100vh', background: '#f5e8d6', fontFamily: "'Lato', sans-serif" }}>
      <Navbar activePage="recommendations" onLogout={onLogout} />

      <div style={{ padding: '2.5rem 2.5rem', maxWidth: '780px', margin: '0 auto' }}>

        <PageHeader
            title="Your Reading Portrait"
            subtitle="A personal analysis generated by AI based on your library"
        />

        <ErrorBanner message={error} />

        {/* No recommendation yet */}
        {!recommendation && !error && (
          <div style={{ background: colors.cream, border: `1px solid ${colors.linen}`, borderRadius: '16px', padding: '3rem', textAlign: 'center' }}>
            <div style={{ fontFamily: '"Playfair Display", Georgia, serif', fontSize: '20px', color: colors.ink, marginBottom: '8px' }}>
              No recommendation yet
            </div>
            <div style={{ fontSize: '13px', color: '#9c7a52', marginBottom: '2rem', lineHeight: 1.7 }}>
              Novelle AI will analyze your library and create a personalized reading portrait just for you.
            </div>
            <button
              onClick={fetchRecommendation}
              disabled={generating}
              style={{ background: colors.berry, color: colors.cream, border: 'none', borderRadius: '8px', padding: '12px 28px', fontSize: '12px', letterSpacing: '0.12em', textTransform: 'uppercase', fontFamily: "'Lato', sans-serif", fontWeight: 700, cursor: 'pointer', opacity: generating ? 0.7 : 1 }}
            >
              {generating ? 'Generating...' : 'Generate my portrait'}
            </button>
          </div>
        )}

        {/* Recommendation card */}
        {recommendation && (
          <div style={{ background: colors.cream, border: `1px solid ${colors.linen}`, borderRadius: '16px', overflow: 'hidden' }}>

            {/* Banda rosie */}
            <div style={{ background: colors.berry, padding: '1.4rem 3rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div style={{ fontSize: '11px', color: `${colors.linen}aa`, letterSpacing: '0.1em', textTransform: 'uppercase' }}>
                A letter from <strong style={{ color: colors.linen }}>Novelle AI</strong>
              </div>
              <div style={{ fontSize: '11px', color: `${colors.linen}88`, fontStyle: 'italic', fontFamily: '"Playfair Display", serif' }}>
                {today}
              </div>
            </div>

            {/* Rows */}
            <div style={{ padding: '0 3rem' }}>
              {rows.map((row, i) => (
                <div key={row.key} style={{
                  display: 'flex', alignItems: 'flex-start', gap: '1.5rem',
                  padding: '1.4rem 0',
                  borderBottom: i < rows.length - 1 ? `1px solid ${colors.parchment}` : 'none',
                }}>
                  <div style={{ width: '34px', height: '34px', borderRadius: '50%', background: row.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: '2px' }}>
                    {row.icon}
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: '10px', letterSpacing: '0.12em', textTransform: 'uppercase', fontWeight: 700, marginBottom: '5px', color: row.color }}>
                      {row.label}
                    </div>
                    <div style={{ fontFamily: '"Playfair Display", Georgia, serif', fontSize: '15px', color: colors.ink, fontWeight: 400, marginBottom: '4px', lineHeight: 1.5 }}>
                      <ReactMarkdown>{recommendation[row.key] || '—'}</ReactMarkdown>
                    </div>
                    <div style={{ fontSize: '12px', color: '#9c7a52', lineHeight: 1.7, fontStyle: 'italic', fontFamily: '"Playfair Display", serif' }}>
                      {row.desc(recommendation[row.key])}
                    </div>
                    <div style={{ display: 'inline-block', borderRadius: '20px', padding: '3px 12px', fontSize: '10px', fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', marginTop: '8px', background: row.bg, color: row.color }}>
                      {row.tag}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Footer */}
            <div style={{ padding: '1.4rem 3rem', borderTop: `1px solid ${colors.parchment}`, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div style={{ fontFamily: '"Playfair Display", serif', fontStyle: 'italic', fontSize: '16px', color: colors.warmOak }}>
                With love, Novelle 
              </div>
              <button
                onClick={fetchRecommendation}
                disabled={generating}
                style={{ background: colors.blueberry, color: colors.cream, border: 'none', borderRadius: '8px', padding: '9px 18px', fontSize: '11px', letterSpacing: '0.1em', textTransform: 'uppercase', fontFamily: "'Lato', sans-serif", fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', opacity: generating ? 0.7 : 1 }}
              >
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#fdf8f0" strokeWidth="2">
                  <polyline points="23 4 23 10 17 10"/>
                  <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
                </svg>
                {generating ? 'Generating...' : 'Regenerate'}
              </button>
              <div style={{ fontSize: '10px', color: '#9c7a52', fontStyle: 'italic' }}>
                Updates after 5+ library changes
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}